// Derives the splash globe placard's country count from data/journey.json
// and writes it to src/generated/splash-stats.ts. Called from build.ts and
// dev.ts before bundling, so the splash chunk gets one integer instead of
// the full 19 KB waypoint list (the splash entry deliberately keeps data
// imports out — see the bundle-guard comments in Splash.tsx).
//
// The generated file is committed so a fresh checkout typechecks without
// running a build first; every build/dev boot rewrites it from source.

import { writeFileSync, readFileSync } from 'node:fs';
import { canonicalVisitedNames, NON_COUNTRY_NAMES } from '../src/globe/visited-aliases';

interface JourneyJson {
  waypoints: Array<{ label: string }>;
}

export function buildSplashStats(): number {
  const journey = JSON.parse(
    readFileSync('./data/journey.json', 'utf8'),
  ) as JourneyJson;
  const canonical = canonicalVisitedNames(journey.waypoints.map((w) => w.label));
  // The globe paints every visited place; the stat counts countries only.
  const count = [...canonical].filter((n) => !NON_COUNTRY_NAMES.has(n)).length;

  const banner =
    '// AUTO-GENERATED by scripts/build-splash-stats.ts — do not edit.\n' +
    '// Regenerated on every `bun run dev` / `bun run build` from\n' +
    '// data/journey.json. Committed so fresh checkouts typecheck.\n';
  writeFileSync(
    './src/generated/splash-stats.ts',
    `${banner}\nexport const VISITED_COUNTRY_COUNT = ${count};\n`,
  );
  return count;
}
