// Generates src/generated/splash-content.ts — the splash's entire data
// surface — from two sources:
//
//   data/splash.json  — splash-authored content (door curation, tagline,
//                       continent count). Small, prose-free, owner-edited.
//   data/me.json      — derived identity: name, portrait, social handles
//                       (contact_information is the single source of
//                       truth; the splash can no longer drift from it).
//   data/journey.json — visited-country count (via the shared alias +
//                       non-country rules in src/globe/visited-aliases.ts).
//
// Called from build.ts and dev.ts before bundling. This is the
// bundle-guard mechanism: the splash entry imports the tiny generated
// module instead of me.json, so none of the resume prose enters the
// chrome-only chunk. The generated file is committed so fresh checkouts
// typecheck; every build/dev boot rewrites it.
//
// Supersedes scripts/build-splash-stats.ts (2026-07-22).

import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { canonicalVisitedNames, NON_COUNTRY_NAMES } from '../src/globe/visited-aliases';

interface JourneyJson {
  waypoints: Array<{ label: string }>;
}

interface SplashDoor {
  id: string;
  href: string;
  thumb: string;
  label: string;
  sublabel: string;
  cta: string;
  aria: string;
}

interface SplashJson {
  tagline: string;
  continent_count: number;
  doors: SplashDoor[];
  explorer: Omit<SplashDoor, 'id' | 'thumb'>;
}

interface MeJson {
  contact_information: {
    name: string;
    portrait: string;
    email: string;
    github: string;
    linkedin: string;
    twitter: string;
    instagram: string;
    threads: string;
  };
}

// Splash social order — icons resolve from these ids in Splash.tsx.
const SOCIAL_ORDER = ['github', 'linkedin', 'twitter', 'instagram', 'threads', 'email'] as const;
const SOCIAL_LABELS: Record<(typeof SOCIAL_ORDER)[number], string> = {
  github: 'GitHub',
  linkedin: 'LinkedIn',
  twitter: 'X (Twitter)',
  instagram: 'Instagram',
  threads: 'Threads',
  email: 'Email',
};

export function buildSplashContent(): void {
  const journey = JSON.parse(readFileSync('./data/journey.json', 'utf8')) as JourneyJson;
  const splash = JSON.parse(readFileSync('./data/splash.json', 'utf8')) as SplashJson;
  const ci = (JSON.parse(readFileSync('./data/me.json', 'utf8')) as MeJson).contact_information;

  const canonical = canonicalVisitedNames(journey.waypoints.map((w) => w.label));
  // The globe paints every visited place; the stat counts countries only.
  const visitedCountryCount = [...canonical].filter((n) => !NON_COUNTRY_NAMES.has(n)).length;

  const socials = SOCIAL_ORDER.map((id) => ({
    id,
    href: id === 'email' ? `mailto:${ci.email}` : ci[id],
    label: SOCIAL_LABELS[id],
  }));

  const out = [
    '// AUTO-GENERATED by scripts/build-splash-content.ts — do not edit.',
    '// Regenerated on every `bun run dev` / `bun run build` from',
    '// data/splash.json + data/me.json + data/journey.json.',
    '// Committed so fresh checkouts typecheck.',
    '',
    `export const VISITED_COUNTRY_COUNT = ${visitedCountryCount};`,
    `export const CONTINENT_COUNT = ${splash.continent_count};`,
    `export const SPLASH_NAME = ${JSON.stringify(ci.name)};`,
    `export const SPLASH_PORTRAIT = ${JSON.stringify('/' + ci.portrait.replace(/^\//, ''))};`,
    `export const SPLASH_TAGLINE = ${JSON.stringify(splash.tagline)};`,
    `export const SOCIALS = ${JSON.stringify(socials, null, 2)} as const;`,
    `export const DOORS = ${JSON.stringify(splash.doors, null, 2)} as const;`,
    `export const EXPLORER_DOOR = ${JSON.stringify(splash.explorer, null, 2)} as const;`,
    '',
  ].join('\n');
  mkdirSync('./src/generated', { recursive: true });
  writeFileSync('./src/generated/splash-content.ts', out);
}
