// Shared data shapes for the resume site.
// All content lives in data/me.json — there's no global media pool.
// Media attaches inline to whichever entry it belongs to.

// ----- Mode + visibility ----------------------------------------------

export type Mode = 'interactive' | 'text' | '1pager';

// Where this item shows up. Replaces the legacy numeric `priority` /
// `omit` pair on every renderable node.
//   all         → interactive + text + 1pager
//   not_1pager  → interactive + text  (DEFAULT — applied when missing)
//   1pager_only → 1pager only
//   archived    → never rendered (kept in the JSON as history)
export type Visibility = 'all' | 'not_1pager' | '1pager_only' | 'archived';

export type RichText = string | { text: string; short?: string; visibility?: Visibility };

// ----- Media (formerly photos.json + uis.json + per-entry slots) -------

type MediaType = 'image' | 'video' | 'embed';
type MediaLayout = 'stack' | 'strip' | 'carousel' | 'grid';
// Lightbox treatment. 'ui' renders the about-text in a dedicated side/bottom
// panel beside the screenshot; 'photo' (default when omitted) keeps the
// existing bottom gradient caption overlay. Opt-in via me.json.
type MediaSubtype = 'photo' | 'ui';

// Per-prose-field provenance. Only present when a prose value was
// written (or rewritten) by the LLM in the labels pipeline:
//   'ai'      — raw classifier output
//   'refined' — LLM rewrite informed by the curator's freeform notes
// Absence of an entry means the value is human-authored (curator
// override, me.json item.caption, atlas album title) or structural.
// The lightbox keys off this to render a "by AI" badge next to AI prose.
type ProseProvenanceTier = 'ai' | 'refined';
export interface ProseProvenance {
  caption?: ProseProvenanceTier;
  alt?: ProseProvenanceTier;
  story?: ProseProvenanceTier;
}

export interface MediaItem {
  id: string;
  type: MediaType;
  src: string;
  caption?: string;
  // Descriptive a11y text for screen readers. Different from `caption`,
  // which is editorial display copy ("Motherland."). When `alt` is not
  // authored, render paths fall back to caption. Backfill is a curation
  // task tracked in TODOS.md.
  alt?: string;
  tag?: string;
  aspect?: number;
  poster?: string;
  span?: { col?: number; row?: number };
  subtype?: MediaSubtype;
  // Optional outbound link to the deep catalog. /photographer lightbox
  // renders "View full album →" CTA in chrome when present.
  album_url?: string;
  // Graphic content gate. When true, the lightbox renders the slide
  // blurred behind a "Tap to reveal" overlay until the viewer opts in
  // (mirrors the masonry tile behavior). The masonry strips this flag
  // for photos the viewer already revealed there, so the lightbox only
  // re-gates photos the viewer hasn't seen yet.
  graphic?: boolean;
  // See ProseProvenance above — populated on photography-page items so
  // the lightbox can tag AI-written captions.
  prose_provenance?: ProseProvenance;
}

export interface MediaGroup {
  layout: MediaLayout;
  // `align` and `size` apply when layout is 'stack' (marginalia float).
  align?: 'left' | 'right';
  size?: 'sm' | 'md' | 'lg';
  // Override `layout` on mobile (≤720px). Useful when a desktop strip of
  // mixed-aspect items (e.g. Forecast: phone screenshots + a 16:9 gif)
  // reads better as a swipeable carousel on phone than as the default
  // portrait-split phone gallery + landscape strip.
  mobile_layout?: MediaLayout;
  // Hide the per-item `tag` overlay across the whole group. Strip layouts
  // already suppress tags; this also suppresses them in carousel/grid/
  // stack layouts where tags otherwise sit in the corner of each card.
  hide_tags?: boolean;
  items: MediaItem[];
}

// ----- Lightbox plumbing ----------------------------------------------

export interface MediaContextValue {
  open: (scope: MediaItem[], id: string) => void;
}

// ----- Photography manifest (built at build time) ----------------------
//
// Generated by scripts/build-photography-manifest.ts from three sources
// (me.json sabbatical-travel, data/photography.json, data/photo-atlas.json)
// and embedded inline in dist/photographer/index.html as
// window.__PHOTOGRAPHY_MANIFEST__. The /photographer page reads this once
// on mount with no fetch round trip.

export interface PhotographyEntry {
  id: string;
  // Original src under media/, used for the lightbox full-size fallback
  // when no derived variant exists.
  src: string;
  // Derived sharp variants, paths under media/portfolio/derived/.
  // Absent on photos whose source predates the build pipeline (atlas
  // tiles already pre-sized in media/portfolio/, sabbatical-travel
  // photos in media/sabbatical-travel/ — sharp still generates 3 variants
  // into derived/ for those too).
  src_tile?: string;
  src_medium?: string;
  src_full?: string;
  aspect: number;
  caption?: string;
  alt?: string;
  theme?: string[];
  // ISO-3166-1 alpha-3 code (lowercase: usa, deu, gbr, ata, ...).
  // Display layer maps this to a human-readable country name via the
  // manifest's `countries` array (which carries name + continent).
  country?: string;
  // Optional sub-national location detail. Curator-authored via the
  // review tool's structured-overrides panel; the refinement LLM may
  // also fill these from curator notes when notes mention a place.
  city?: string;
  state?: string;
  // Open-ended subjects/objects visible in the photo (animals, plants,
  // vehicles, landmarks, people-as-roles). Populated by
  // scripts/classify-photography.ts; freeform, not used for filtering.
  entities?: string[];
  // Common-English species name when the photo is wildlife.
  species?: string;
  // 1-3 sentence narrative interpretation written by the classifier.
  story?: string;
  album_url?: string;
  featured?: boolean;     // hero-eligible (sabbatical-travel photos default to true)
  // Graphic content: tile renders blurred behind a "tap to reveal"
  // overlay in the masonry. Authored per-photo in data/photography.json.
  graphic?: boolean;
  // Curator marker — "this photo is the same as that one." Set via the
  // review tool's mark-dupe button. Carried through the manifest so
  // downstream filters can choose to hide one of the duplicates. The
  // build itself doesn't drop dupes; that's left to the display layer.
  dupeOf?: string;
  // Curator-assigned global ranking (lower wins — top of the array is
  // the best photo). Set via the review tool's list-view drag-and-drop
  // "Save order" gesture. The manifest builder sorts photos by this
  // field ascending nulls-last so every downstream consumer inherits
  // the ranking without each one re-sorting. Absent on photos the
  // curator hasn't ranked — those keep their original source-file order
  // relative to each other and fall to the end behind ranked photos.
  sort_order?: number;
  // Per-photo critique scores produced by scripts/photography-crit.ts.
  // Five sub-dimensions plus a holistic 0-100 overall score plus a
  // 1-3 sentence critique. The overall is the model's holistic call,
  // not a mean of the sub-scores.
  crit_score?: number;
  crit_composition?: number;
  crit_lighting?: number;
  crit_subject?: number;
  crit_emotion?: number;
  crit_technical?: number;
  // Per-dimension notes — one sentence each, written by the same
  // crit pass. Pair with the matching score above for display.
  crit_composition_notes?: string;
  crit_lighting_notes?: string;
  crit_subject_notes?: string;
  crit_emotion_notes?: string;
  crit_technical_notes?: string;
  // Synthesis across all dimensions: 2-3 sentences ending with a
  // concrete suggested change.
  crit_notes?: string;
  // Per-prose-field provenance — see ProseProvenance for semantics.
  prose_provenance?: ProseProvenance;
}

export interface PhotographyManifest {
  photos: PhotographyEntry[];
  // Unique theme tags across photos, sorted by photo count desc.
  themes: string[];
  // Unique species across photos, sorted by photo count desc. Populated
  // from the classifier output (scripts/classify-photography.ts).
  species: string[];
  // Species grouped by their wildlife sub-class (birds / mammals /
  // reptiles-amphibians / marine-life / insects / flora). Assigned at
  // build time by counting which class tag co-occurs most often with
  // each species in photo.theme[]. Powers the species-as-leaves view
  // in CategoryDropdown.
  speciesByClass: Record<string, string[]>;
  // Unique countries across photos, sorted by display name asc. The
  // `continent` field powers the grouped Location filter; assigned at
  // build time from a static slug→continent map (see scripts/build-photography-manifest.ts).
  countries: { slug: string; name: string; continent: string }[];
}

// Window globals injected by build.ts template injection.
declare global {
  interface Window {
    __PHOTOGRAPHY_MANIFEST__?: PhotographyManifest;
  }
}

// ----- Resume top-level -----------------------------------------------

export interface Contact {
  // Full legal name. Used in places that want the formal identity (e.g.,
  // the printed 1-pager). For Google search display, OG titles, and the
  // JSON-LD Person schema, prefer `display_name`.
  name: string;
  // Search-friendly display name (drops middle names, suffixes, etc).
  // Source of truth for the Person schema's `name` field and most
  // social-share titles. Lives in me.json so it can change without code.
  display_name: string;
  // schema.org Person split. Both required because schema.org's
  // `Person.givenName` / `Person.familyName` are independent fields, not
  // derived from `name`.
  given_name: string;
  family_name: string;
  // Short bio used as schema.org Person.jobTitle and as the og:description
  // on the splash page. Distinct from the longer prose in `summary`.
  tagline: string;
  // Project-relative path to the canonical portrait image (no leading
  // slash). Consumed by build.ts/dev.ts to build the absolute URL used in
  // the JSON-LD Person.image field and the splash's secondary og:image.
  portrait: string;
  address: string;
  website: string;
  email: string;
  phone: string;
  linkedin: string;
  github: string;
  twitter: string;
  instagram?: string;
  threads?: string;
}

export interface Achievement {
  text: string;
  short?: string;
  visibility?: Visibility;
}

interface ProjectMetrics {
  commits?: number;
  lines_added?: number;
  lines_removed?: number;
  private_repos?: number;
  methodology?: string;
}

export interface Project {
  name: string;
  repo?: string;
  url?: string;
  visibility?: Visibility;
  description: string | { text: string };
  stack?: string[];
  metrics?: ProjectMetrics;
}

export interface Track {
  period: string;
  focus: string;
  visibility?: Visibility;
  tagline?: string;
  summary?: string;
  summary_1pager?: string;
  metrics?: ProjectMetrics;
  toolchains?: string[];
  achievements?: Achievement[];
  projects?: Project[];
  // Inline media for this track (e.g., the Travel carousel).
  media?: MediaGroup;
  // Inline reviews block (e.g., the Real Estate Airbnb testimonials).
  reviews?: ReviewsData;
}

export interface Era {
  period: string;
  focus: string;
  role?: string;
  visibility?: Visibility;
  achievements?: Achievement[];
  // Inline media for this era (e.g., Forecast UIs, Pro Mode hero).
  media?: MediaGroup;
  // Single-paragraph description used on the generic /builder/ page in
  // place of the bulleted achievements. When absent, EraGeneric falls
  // back to the first achievement's text. Never shown on /resume/.
  builder_tagline?: string;
}

export interface Job {
  company: string;
  shortened_title?: string;
  role: string;
  location?: string;
  start_date: string;
  end_date: string;
  visibility?: Visibility;
  summary?: string;
  achievements?: (Achievement | string)[];
  tracks?: Track[];
  eras?: Era[];
  inline?: boolean;
  // Inline media at the job level (e.g., Bluenose UIs).
  media?: MediaGroup;
  // Hide this job entirely from the generic /builder/ page (Builder.tsx).
  // /resume/ still renders it. Use for short / older roles you don't
  // want on the public-facing intro.
  hide_on_builder?: boolean;
}

export interface School {
  institution: string;
  degree: string;
  degree_short?: string;
  location?: string;
  start_date: string;
  end_date: string;
  visibility?: Visibility;
  details?: Achievement[];
}

export interface SkillSet {
  domains?: (Achievement | string)[];
  stack?: (Achievement | string)[];
  force_multipliers?: (Achievement | string)[];
}

export interface CommunityEntry {
  group: string;
  role: string;
  start_date: string;
  end_date: string;
  visibility?: Visibility;
  details?: string | { text: string };
  // Inline media for this community entry (talks, photos, etc.).
  media?: MediaGroup;
}

// Redaction registry — Greek-letter variables that stand in for figures
// intentionally withheld from the public resume. Each entry powers two
// surfaces: the inline anchor + tooltip in running prose (KPText) and
// the Notes section at the end of the resume (RedactionNotes).
export interface Redaction {
  // DOM-safe anchor name. The inline glyph renders as
  // `<a href="#note-{id}">` and the matching footnote `<dt>` carries
  // `id="note-{id}"`. Use lowercase Greek letter names ("alpha", etc).
  id: string;
  // The actual character that appears in me.json prose. Kept
  // narrow on purpose — KPText scans for `[ΞαβσΣΨΩΦ]` only (see
  // REDACTED_GLYPH_RE in me.ts).
  glyph: string;
  // Short context string. Shown in the hover tooltip (desktop) and the
  // Notes section (everywhere). Should describe what the variable
  // represents without revealing the specific numeric value.
  context: string;
}

export interface Resume {
  contact_information: Contact;
  summary: string;
  // Top-level summary gallery (was the `summary-gallery` slot).
  summary_media?: MediaGroup;
  experience: Job[];
  education: School[];
  skills: SkillSet;
  community_organization: CommunityEntry[];
  redactions?: Redaction[];
}

// ----- Reviews (Airbnb testimonials) ----------------------------------

export interface Review {
  reviewer: string;
  location: string;
  rating: number;
  date: string;
  stay_type?: string;
  review: string;
  translation?: string;
  // Phrases to mark inside the original-language `review`. Substrings,
  // case-insensitive, must appear verbatim in the source text.
  host_highlights?: string[];
  // Phrases to mark inside `translation` when the user toggles to English.
  // Authored separately because translated text rarely contains the same
  // strings as the original-language source. Falls back to no highlights
  // if missing on a translated review.
  translation_highlights?: string[];
}

export interface ReviewsData {
  listing: string;
  listing_url?: string;
  host: string;
  overall_rating: number;
  total_reviews: string;
  best_host_reviews: Review[];
  recurring_host_praise_themes?: string[];
}
